Repository essence-community/core-backend, pull requests merged in 2020-05, with the labels that each got.

#266 CORE-1719 fixed id for class
  dbms/meta/MetaClass.sql
Labels: bug

#267 fix auth liquibase
  dbms_auth/s_mt/scripts.sql
Labels: bug

#268 fix auth sql 2
  dbms_auth/s_mt/scripts.sql
Labels: bug

#269 CORE-1732 changed description for imask
  dbms/meta/MetaClass.sql
Labels: documentation

#270 CORE-1185 fix class
  dbms/meta/MetaClass.sql
Labels: bug

#271 CORE-1725 new UI attributes for filter and filter extended
  dbms/meta/MetaClass.sql
Labels: enhancement

#272 CORE-1725 btnfilter attribute for hide filter in column
  dbms/meta/MetaClass.sql
Labels: enhancement

#273 CORE-1710 migrated ws gate url into sys setting
  dbms/s_mt/scripts.sql
Labels: enhancement

#274 CORE-1746 maxselected attribute
  dbms/meta/MetaClass.sql
Labels: enhancement

#275 CORE-1182 add locale
  dbms/s_mt/scripts.sql
Labels: enhancement

#276 CORE-1761 field color class
  dbms/meta/MetaClass.sql
Labels: enhancement

#277 init 2.4.0
  VERSION
  package.json
  server/package.json
Labels: enhancement

#279 CORE-1772
  dbms/meta/scripts.sql
Labels: bug

#278 CORE-1772
  dbms/meta/scripts.sql
Labels: bug
