Repository essence-community/core-backend, pull requests merged in 2020-06, with the labels that each got.

#282 CORE-1782 migrated attributes to boolean
  dbms/meta/MetaClass.sql
  dbms/s_mt/scripts.sql
Labels: enhancement

#284 CORE-1782 updated page
  dbms/meta/page/Page_1.sql
  dbms/meta/page/Page_12127721.sql
  dbms/meta/page/Page_12128581.sql
  dbms/meta/page/Page_12987721.sql
  dbms/meta/page/Page_1626AD0E15B446D4B478CCC5AC2B6E60.sql
  dbms/meta/page/Page_181.sql
  dbms/meta/page/Page_1875398035771.sql
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_25887721.sql
  dbms/meta/page/Page_268357780361.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_302.sql
  dbms/meta/page/Page_318AD0CA3F00478B95556ADBBE58E758.sql
  dbms/meta/page/Page_4.sql
  dbms/meta/page/Page_483653E7F5BC481D86375F5A3C803AC2.sql
  dbms/meta/page/Page_5.sql
  dbms/meta/page/Page_652.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/meta/page/Page_87C1A7620D9D4B35A9AD2460DB3A2358.sql
  dbms/meta/page/Page_BC4B5C748874439E9CED6E8F76933B84.sql
  dbms/meta/page/Page_DDBEA79C5CBE4DC3A2CEA74DA46216A7.sql
  dbms/meta/page/Page_F5CAF3CF206A4454A48FA1466932B969.sql
  dbms/meta/page/page.xml
  dbms_auth/meta/page/Page_5868BCACDD034DFF9DC9B0C3170CB720.sql
  dbms_auth/meta/page/Page_6230F0855D6648C9A0CDBE62ED1B1811.sql
  dbms_auth/meta/page/Page_8F285F5F5D6742E7BC795751DBB9E55B.sql
  dbms_auth/meta/page/Page_CF6B6D22EE0E4524A7FF6727BC51C0FA.sql
  dbms_auth/meta/page/Page_D9ED58074C5F4972A5CEEED5B35FFCC7.sql
  dbms_auth/meta/page/Page_F010FF49A7FD4F63A5E0B070B9AD2536.sql
Labels: enhancement

#285 CORE-1236 fix ck_attr_type
  dbms/t_query/MTAttr.sql
Labels: bug

#286 CORE-1787 migrated fields into number, css measure
  dbms/meta/MetaClass.sql
  dbms/meta/page/Page_1.sql
  dbms/meta/page/Page_12128581.sql
  dbms/meta/page/Page_12987721.sql
  dbms/meta/page/Page_181.sql
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_318AD0CA3F00478B95556ADBBE58E758.sql
  dbms/meta/page/Page_652.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/s_mp/pkg_json.sql
  dbms/s_mp/pkg_meta.sql
  dbms/s_mt/scripts.sql
  dbms_auth/meta/page/Page_8F285F5F5D6742E7BC795751DBB9E55B.sql
  dbms_auth/meta/page/Page_D9ED58074C5F4972A5CEEED5B35FFCC7.sql
Labels: enhancement

#287 CORE-1787 fixed editmode for hidden
  dbms/meta/page/Page_1.sql
  dbms/meta/page/Page_12128581.sql
  dbms/meta/page/Page_12987721.sql
  dbms/meta/page/Page_181.sql
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_268357780361.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_318AD0CA3F00478B95556ADBBE58E758.sql
  dbms/meta/page/Page_652.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/meta/page/Page_F5CAF3CF206A4454A48FA1466932B969.sql
  dbms/s_mt/scripts.sql
Labels: bug, enhancement

#288 CORE-1791 migrated part of attributes into enums
  dbms/meta/MetaClass.sql
  dbms/s_mt/scripts.sql
  dbms/t_query/MTEnumAttr.sql
Labels: enhancement

#289 CORE-1239 redesign application
  contexts/CorePGContext/src/CoreContext.ts
  contexts/CorePGContext/src/ICoreController.ts
  contexts/CorePGContext/src/OfflineController.ts
  contexts/CorePGContext/src/OnlineController.ts
  contexts/CorePGContext/src/TempTable.ts
  contexts/CorePGContext/src/Util.ts
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_EFFC1868B5804AABAAF7EE516BD24952.sql
  dbms/meta/page/page.xml
  dbms/s_mt/scripts.sql
  dbms/t_query/MTApplicationRoute.sql
  dbms/t_query/query.xml
  plugininf/lib/NullContext.ts
  server/src/http/controllers/MainController.ts
Labels: enhancement

#290 CORE-1239 fix
  contexts/CorePGContext/src/OnlineController.ts
  contexts/CorePGContext/src/TempTable.ts
  plugininf/lib/db/oracle/OracleDB.ts
  plugininf/lib/db/postgres/PostgresDB.ts
Labels: bug

#291 CORE-1254 fix localization value
  dbms/s_mp/pkg_meta.sql
Labels: bug

#294 CORE-1798 promo class
  dbms/meta/MetaClass.sql
Labels: enhancement

#295 CORE-1800 classes and functions for documentation
  dbms/meta/MetaClass.sql
  dbms/meta/page/Page_182033F620954FD3B4052BE7CBFD4071.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_AB115A267226428A9B23F1E7BE09028D.sql
  dbms/meta/page/page.xml
  dbms/s_mp/pkg_json_meta.sql
  dbms/s_mp/pkg_meta.sql
  dbms/s_mt/scripts.sql
  dbms/t_query/DTRoute.sql
  dbms/t_query/MTClassDoc.sql
  dbms/t_query/query.xml
Labels: enhancement

#296 Core 1257
  dbms/s_mp/pkg_meta.sql
  patcher/patcher-core.jar
Labels: enhancement

#297 CORE-1802 folder for documentation
  dbms/meta/MetaClass.sql
  dbms/meta/page/Page_A732E27B938245A9A4A5047B761CD267.sql
  dbms/meta/page/Page_C0EF204A8D77489FB097AC43A481818D.sql
  dbms/meta/page/Page_C8AB48295BF9484C9AAB10D8B35F0D92.sql
  dbms/meta/page/Page_E3B71F02EC584D619DCBA77ED1CF8F4E.sql
  dbms/meta/page/page.xml
  dbms/s_mt/scripts.sql
  dbms/t_query/DTRoute.sql
Labels: enhancement

#298 CORE-1258 fix MTRoute and DTRoute
  dbms/t_query/DTRoute.sql
  dbms/t_query/MTRoute.sql
Labels: bug

#299 CORE-1258 fix DTRoute
  dbms/t_query/DTRoute.sql
Labels: bug

#300 Core 1802
  dbms/meta/MetaClass.sql
  dbms/meta/page/Page_6DEAA83AAB72473CA2271A7CEC29C19D.sql
  dbms/meta/page/Page_914836A8F7734C5DA29CC3E03677685F.sql
  dbms/meta/page/Page_A732E27B938245A9A4A5047B761CD267.sql
  dbms/meta/page/Page_AB115A267226428A9B23F1E7BE09028D.sql
  dbms/meta/page/Page_BCF372022D324CF691035DBBB893289C.sql
  dbms/meta/page/Page_C0EF204A8D77489FB097AC43A481818D.sql
  dbms/meta/page/Page_C5251BA9B0924B4BB500ACF3D6352157.sql
  dbms/meta/page/page.xml
  dbms/s_mt/scripts.sql
  dbms/t_query/DTRoute.sql
Labels: documentation, enhancement

#301 CORE-1805 default querymode = locale for field combobox
  dbms/meta/MetaClass.sql
Labels: enhancement

#302 CORE-1801 error boundary message
  dbms/meta/page/Page_A732E27B938245A9A4A5047B761CD267.sql
  dbms/s_mt/scripts.sql
Labels: documentation, enhancement

#303 Core 1796
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_BCF372022D324CF691035DBBB893289C.sql
Labels: documentation, enhancement

#304 CORE-1256 add lvl change to plugin
  plugininf/@types/rufus/index.d.ts
  plugininf/lib/ICCTParams.ts
  plugininf/lib/Logger.ts
  plugininf/lib/NullContext.ts
  plugininf/lib/NullPlugin.ts
  plugininf/lib/NullProvider.ts
  plugininf/lib/db/oracle/OracleDB.ts
  plugininf/lib/db/postgres/PostgresDB.ts
  providers/AdAuth/src/AdAuth.ts
  providers/AuthCrmWs/src/AuthCrmWs.ts
  providers/CoreAuthOracle/src/CoreAuthOracle.ts
  providers/CoreAuthPG/src/CoreAuthPg.ts
Labels: bug, enhancement

#306 Core 1265 add provider redis
  plugins/PrepareQuery/src/PrepareQuery.ts
  plugins/S3Storage/src/S3Storage.ts
  providers/Redis/package.json
  providers/Redis/src/RedisProvider.ts
  providers/Redis/src/index.ts
  providers/Redis/tsconfig.json
  server/src/core/Constants.ts
  server/src/core/request/RequestContext.ts
  server/src/http/controllers/GlobalController.ts
  server/src/http/controllers/ResultController.ts
  yarn.lock
Labels: enhancement

#307 fix oracle
  plugininf/lib/NullContext.ts
  plugininf/lib/NullPlugin.ts
  plugininf/lib/NullProvider.ts
  plugininf/lib/db/oracle/OracleDB.ts
Labels: bug

#305 Core 1792
  dbms/meta/MetaClass.sql
  dbms/meta/page/Page_1.sql
  dbms/meta/page/Page_12128581.sql
  dbms/meta/page/Page_12987721.sql
  dbms/meta/page/Page_181.sql
  dbms/meta/page/Page_182033F620954FD3B4052BE7CBFD4071.sql
  dbms/meta/page/Page_1875398035771.sql
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_268357780361.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_652.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/meta/page/Page_AB115A267226428A9B23F1E7BE09028D.sql
  dbms/meta/page/Page_F5CAF3CF206A4454A48FA1466932B969.sql
  dbms/s_mp/pkg_json.sql
  dbms/s_mp/pkg_meta.sql
  dbms/s_mt/scripts.sql
  dbms/t_query/MTObjectAttribute.sql
  dbms/t_query/MTPageObjectAttribute.sql
  dbms_auth/meta/page/Page_8F285F5F5D6742E7BC795751DBB9E55B.sql
  dbms_auth/meta/page/Page_D9ED58074C5F4972A5CEEED5B35FFCC7.sql
Labels: enhancement

#308 CORE-1823 migration for valuefield
  dbms/meta/page/Page_1.sql
  dbms/meta/page/Page_12128581.sql
  dbms/meta/page/Page_12987721.sql
  dbms/meta/page/Page_181.sql
  dbms/meta/page/Page_182033F620954FD3B4052BE7CBFD4071.sql
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_652.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/meta/page/Page_AB115A267226428A9B23F1E7BE09028D.sql
  dbms/meta/page/Page_F5CAF3CF206A4454A48FA1466932B969.sql
  dbms_auth/meta/page/Page_5868BCACDD034DFF9DC9B0C3170CB720.sql
  dbms_auth/meta/page/Page_8F285F5F5D6742E7BC795751DBB9E55B.sql
  dbms_auth/meta/page/Page_CF6B6D22EE0E4524A7FF6727BC51C0FA.sql
  dbms_auth/meta/page/Page_D9ED58074C5F4972A5CEEED5B35FFCC7.sql
  dbms_auth/meta/page/Page_F010FF49A7FD4F63A5E0B070B9AD2536.sql
Labels: bug, enhancement

#309 CORE-1268 check global
  dbms/s_mp/pkg_util.sql
Labels: bug

#311 fix move file
  dbms/meta/scripts.sql
Labels: bug

#312 CORE-1792 convert object attributes
  dbms/meta/page/Page_1.sql
  dbms/meta/page/Page_12128581.sql
  dbms/meta/page/Page_12987721.sql
  dbms/meta/page/Page_181.sql
  dbms/meta/page/Page_182033F620954FD3B4052BE7CBFD4071.sql
  dbms/meta/page/Page_2.sql
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_3.sql
  dbms/meta/page/Page_652.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/meta/page/Page_AB115A267226428A9B23F1E7BE09028D.sql
  dbms/meta/page/Page_F5CAF3CF206A4454A48FA1466932B969.sql
  dbms/s_mt/scripts.sql
  dbms_auth/meta/page/Page_5868BCACDD034DFF9DC9B0C3170CB720.sql
  dbms_auth/meta/page/Page_8F285F5F5D6742E7BC795751DBB9E55B.sql
  dbms_auth/meta/page/Page_D9ED58074C5F4972A5CEEED5B35FFCC7.sql
Labels: bug, enhancement

#313 fix_update getmastervalue
  dbms/meta/scripts.sql
Labels: bug

#314 Init 2.5.0
  VERSION
  package.json
  yarn.lock
Labels: enhancement

#315 CORE-1836 fixed migration for the pages andmigration script
  dbms/meta/page/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/meta/page/Page_6695715415771.sql
  dbms/meta/page/Page_AB115A267226428A9B23F1E7BE09028D.sql
  dbms/s_mt/scripts.sql
Labels: bug

#318 Fix admin
  plugininf/lib/ICCTParams.ts
  plugininf/lib/NullContext.ts
  plugininf/lib/NullProvider.ts
  plugininf/lib/db/oracle/OracleDB.ts
  plugininf/lib/db/postgres/PostgresDB.ts
  providers/CoreAuthPG/src/CoreAuthPg.ts
  server/src/http/admingate/AdminAction.ts
Labels: bug

#317 Fix admin
  plugininf/lib/ICCTParams.ts
  plugininf/lib/NullContext.ts
  plugininf/lib/NullProvider.ts
  plugininf/lib/db/oracle/OracleDB.ts
  plugininf/lib/db/postgres/PostgresDB.ts
  providers/CoreAuthPG/src/CoreAuthPg.ts
  server/src/http/admingate/AdminAction.ts
Labels: bug
