Repository essence-community/core-backend, pull requests merged in 2020-04, with the labels that each got.

#239 CORE-1138 fix proxy param
  providers/ProxyTransparent/src/ProxyTransparent.ts
Labels: bug

#238 CORE-1138 fix proxy param
  providers/ProxyTransparent/src/ProxyTransparent.ts
Labels: bug

#244 CORE-1686 made auth page
  dbms/meta/MetaClass.sql
  dbms/meta/Page_22D2F53FE7E24680917B85D9A95237BD.sql
Labels: enhancement

#247 CORE-1695 new class: field markdown
  dbms/meta/MetaClass.sql
Labels: enhancement

#248 Core 1153 add typing attr
  .vscode/settings.json
  dbms/meta/MetaClass.sql
  dbms/meta/Page_1.sql
  dbms/meta/Page_181.sql
  dbms/meta/Page_2.sql
  dbms/meta/Page_3.sql
  dbms/s_mp/pkg_json.sql
  dbms/s_mp/pkg_json_meta.sql
  dbms/s_mp/pkg_meta.sql
  dbms/s_mp/pkg_patcher.sql
  dbms/s_mt/scripts.sql
  dbms/s_su/grants.sql
  dbms/t_query/MTAttr.sql
  dbms/t_query/MTAttrDataType.sql
  dbms/t_query/MTClassAttr.sql
  dbms/t_query/MTEnumAttr.sql
  dbms/t_query/MTGetValuesByAttr.sql
  dbms/t_query/MTGetValuesForPOA.sql
  dbms/t_query/MTObjectAttribute.sql
  dbms/t_query/MTPageObjectAttribute.sql
  dbms/t_query/query.xml
  patcher/patcher-core.jar
  plugins/Patcher/src/meta/MetaPatch.ts
  plugins/Patcher/src/meta/ObjectAttr.ts
  plugins/Patcher/src/meta/PageObjectAttr.ts
  plugins/Patcher/src/meta/SqlPostgres.ts
Labels: enhancement

#251 Core 1174 add master rule and hiddenrule
  dbms/meta/MetaClass.sql
Labels: enhancement

#252 Core 1709
  contexts/CorePGContext/src/OfflineController.ts
  dbms/meta/Page_22D2F53FE7E24680917B85D9A95237BD.sql
  dbms/s_mt/scripts.sql
  dbms/t_query/MTRoute.sql
  dbms_auth/s_at/scripts.sql
Labels: enhancement

#254 CORE-1160 add index
  dbms/s_mp/pkg_json.sql
  dbms/s_mt/scripts.sql
Labels: bug

#253 CORE-1712 access for demo only for autorized user
  dbms/meta/Page_22D2F53FE7E24680917B85D9A95237BD.sql
Labels: bug

#256 Core 1160
  dbms/s_mp/pkg_json.sql
  dbms/s_mt/scripts.sql
Labels: enhancement

#255 init 2.3.0
  VERSION
  dbms/t_query/GetModuleList.sql
  package.json
  server/package.json
Labels: enhancement

#257 CORE-1160 update aggregtion
  dbms/s_mp/pkg_json.sql
Labels: enhancement

#258 CORE-1160 fix
  dbms/s_mp/pkg_json.sql
Labels: bug

#259 CORE-1163 fix typing
  dbms/meta/Localization_message_ru_RU.sql
  dbms/meta/Page_1.sql
  dbms/meta/Page_2.sql
  dbms/meta/Page_3.sql
  dbms/s_mp/pkg_meta.sql
  dbms/s_mt/scripts.sql
  dbms/t_query/MTAddNotification.sql
  dbms/t_query/MTAttr.sql
  dbms/t_query/MTClassAttr.sql
  dbms/t_query/MTEnumAttr.sql
Labels: bug

#260 Core 1151 template package
  dbms/db.changelog.xml
  dbms_auth/db.changelog.auth.xml
  dbms_auth/db.changelog.meta.xml
  dbms_bpmn_integration/db.changelog.meta.xml
  dbms_integration/db.changelog.integr.xml
  dbms_integration/db.changelog.meta.xml
  package.json
  patcher/patcher-core.jar.md5
  utils/gate-cli/.eslintrc
  utils/gate-cli/.gitignore
  utils/gate-cli/README.md
  utils/gate-cli/bin/create-gate-cli
  utils/gate-cli/bin/gate-cli
  utils/gate-cli/index.js
  utils/gate-cli/package.json
  utils/gate-cli/src/UtilError.ts
  utils/gate-cli/src/index.ts
  utils/gate-cli/src/package/oracle.ts
  utils/gate-cli/src/package/postgres.ts
  utils/gate-cli/src/util.ts
  utils/gate-cli/tsconfig.json
  yarn.lock
Labels: documentation, enhancement

#261 fix module load
  dbms/s_mp/pkg_meta.sql
Labels: bug

#263 CORE-1199 update depend
  contexts/CoreOracleContext/package.json
  contexts/CorePGIntegrationContext/package.json
  events/CoreOracleSemaphore/package.json
  events/CorePgLocalization/package.json
  events/CorePgNotification/package.json
  events/CorePgSemaphore/package.json
  gulpfile.js
  libs/nedb-multi/package.json
  package.json
  plugininf/package.json
  plugins/ExtractorFileToJson/package.json
  plugins/JsonRowColumnExtractor/package.json
  plugins/ModuleStorage/package.json
  plugins/Patcher/package.json
  plugins/PrepareQuery/package.json
  plugins/PrepareQuery/src/PrepareQuery.ts
  plugins/S3Storage/package.json
  plugins/S3Storage/src/S3Storage.ts
  plugins/USPOIntegration/package.json
  providers/AdAuth/package.json
  providers/AuthCrmWs/package.json
  providers/AuthMock/package.json
  providers/CoreAuthOracle/package.json
  providers/CoreAuthPG/package.json
  providers/CoreOracleIntegration/package.json
  providers/CorePGIntegration/package.json
  providers/OracleDb/package.json
  providers/PKOAuth/package.json
  providers/PostgreSQLDb/package.json
  providers/ProjectAuth/package.json
  providers/ProxyTransparent/package.json
  schedulers/ReloadProvider/package.json
  server/package.json
  server/src/core/Constants.ts
  server/src/core/request/RequestContext.ts
  server/src/http/controllers/GlobalController.ts
  server/src/http/controllers/ResultController.ts
  yarn.lock
Labels: dependencies

#264 CORE-1719 migrated columns to ts
  dbms/meta/MetaClass.sql
Labels: enhancement

#265 fix load
  dbms/s_mp/pkg_meta.sql
Labels: bug
